version: "3.9"
services:
  dbt:
    image: python:3.11-slim  # Use a Python base image
    container_name: dbt-container
    environment:
      DBT_PROFILES_DIR: /dbt/mem_dwh  # Set profiles directory path
    volumes:
      - dbt-data:/dbt  # Use a named volume for persistence
    networks:
      - default
    command: >
      sh -c "
      apt-get update &&
      apt-get install -y git &&
      git init /dbt &&
      cd /dbt &&
      git remote add origin https://github.com/<your_username>/<your_repo>.git &&
      git config core.sparseCheckout true &&
      echo '/dbt/' > .git/info/sparse-checkout &&
      echo '!/dbt_clickhouse/' >> .git/info/sparse-checkout &&
      git pull origin main &&
      cd /dbt/mem_dwh &&
      pip install dbt-postgres &&
      dbt deps &&
      dbt seed &&
      dbt run &&
      dbt test
      "
    restart: "no"

volumes:
  dbt-data:

networks:
  default:
    name: shared-network
    external: true
