version: '3.8'

services:
  dbt:
    build:
      context: .
      dockerfile: Dockerfile  # Reference the Dockerfile in the same directory
    container_name: dbt
    ports:
      - 8000:8000  # Optional, can be removed if not needed
    environment:
      DBT_PROFILES_DIR: /root/.dbt
    volumes:
      - ./dbt_project:/dbt  # Mount the DBT project directory
    depends_on:
      - pgduckdb
    restart: always
    networks:
      - shared-network

networks:
  shared-network:
    external: true  # Use the same network as pgduckdb

volumes:
  dbt_data:
