version: "3.9"
services:
  dbt:
    image: python:3.11-slim
    container_name: dbt-container
    environment:
      DBT_PROFILES_DIR: /dbt/mem_dwh  # Set profiles directory path
    volumes:
      - dbt-data:/dbt  # Use a named volume for persistence

    ports:
      - 8080:8080
    networks:
      - default
    command: >
      sh -c "
      apt-get update &&
      apt-get install -y git &&
      pip install dbt-postgres &&
      if [ -d /dbt/mem_dwh ]; then
        cd /dbt/mem_dwh &&
        dbt deps &&
        dbt seed &&
        dbt run &&
        dbt test
      else
        echo 'Directory /dbt/mem_dwh not found!' && exit 1
      fi
      "
    restart: "no"

volumes:
  dbt-data:

networks:
  default:
    name: shared-network
    external: true
