version: "3.9"
services:
  dbt:
    image: python:3.11-slim  # Use a Python base image
    container_name: dbt-container
    environment:
      DBT_PROFILES_DIR: /dbt/mem_dwh  # Use absolute path for profiles.yml directory
    volumes:
      - ./local-dbt-project:/dbt  # Correctly mount the local DBT project directory
    ports:
      - 8090:8090
    networks:
      - shared-network  # Ensures accessibility from other containers
    command: >
      sh -c "
      set -e &&
      apt-get update &&
      apt-get install -y git &&
      pip install dbt-core dbt-postgres &&
      echo 'Running DBT commands...' &&
      cd /dbt &&
      dbt debug &&
      dbt deps &&
      dbt run &&
      dbt test &&
      echo 'DBT commands completed.' &&
      sleep infinity
      "
    restart: "always"  # Ensures the container restarts automatically if it stops

volumes:
  local-dbt-project:
    driver: local  # Ensures it uses a local directory for mounting

networks:
  shared-network:
    external: true  # Ensures the network can be shared with other containers
