version: "3.9"
services:
  dbt:
    image: python:3.11-slim  # Use a Python base image
    container_name: dbt-container
    environment:
      DBT_PROFILES_DIR: /dbt/mem_dwh  # Set profiles directory path
    volumes:
      - ./:/dbt  # Mount the entire dbt folder to /dbt in the container
    networks:
      - default
    command: >
      sh -c "
      pip install dbt-postgres &&
      cd /dbt/mem_dwh &&
      dbt deps &&
      dbt seed &&
      dbt run &&
      dbt test
      "
    restart: "no"

networks:
  default:
    name: shared-network
    external: true
