mem_dwh:
  outputs:
    dev:
      dbname: postgres
      host: 192.168.100.130
      password: duckdb
      port: 5444
      schema: public
      threads: 1
      type: postgres
      user: postgres
  target: dev
