# Use a base image with Python
FROM python:3.9-slim

# Set environment variables for DBT profiles directory
ENV DBT_PROFILES_DIR=/app/dbt/

# Set the working directory inside the container
WORKDIR /app/dbt

# Copy the dbt project files from the local directory to the container
COPY ./dbt/dbt_project.yml /app/dbt/
COPY ./dbt/profiles.yml /app/dbt/profiles.yml

# Install DBT and DBT-ClickHouse dependencies
RUN pip install --no-cache-dir dbt-core dbt-clickhouse

# Define the command to run when the container starts
CMD ["bash", "-c", "dbt deps && dbt seed && dbt run && dbt test"]
