services:
  hydra:
    container_name: hydra
    image: ghcr.io/hydradatabase/hydra:latest
    ports:
      - ${POSTGRES_PORT}:5433
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      VIRTUAL_HOST: dwh-hydra.rihal.dev
      VIRTUAL_PORT: 5433
    volumes:
      - volumes-db:/var/lib/postgresql/data
      - files-postgres:/etc/postgresql
      - volumes-backup:/var/lib/pgsql/backups
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    #networks:
      #- default      
 
    #networks:
      #- default

volumes:
  volumes-db:
  files-postgres:
  volumes-backup:
 
networks:
  shared-network:
    external: true
 

