services:
  hydra:
    container_name: dwh-hydra
    image: ghcr.io/hydradatabase/hydra:latest
    #ports:
      #- ${POSTGRES_PORT}:5432
    environment:
      VIRTUAL_HOST: dwh-hydra.rihal.dev
      VIRTUAL_PORT: 5435
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      
    volumes:
      - volumes-db:/var/lib/postgresql/data
      - files-postgres:/etc/postgresql
      - volumes-backup:/var/lib/pgsql/backups
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    networks:
      - hydra-network      
 
    #networks:
      #- default

volumes:
  volumes-db:
  files-postgres:
  volumes-backup:
 
networks:
  hydra-network:
  shared-network:
    external: true

 

