services:
  hydra:
    container_name: dwh-hydra
    image: ghcr.io/hydradatabase/hydra:latest
    ports:
      - 5435:5432
    environment:

      POSTGRES_USER: postgres #${POSTGRES_USER}
      POSTGRES_PASSWORD: hydra #${POSTGRES_PASSWORD}
      POSTGRES_DB: hydra #${POSTGRES_DB}
      
    volumes:
      - volumes-db:/var/lib/postgresql/data
      - files-postgres:/etc/postgresql
      - volumes-backup:/var/lib/pgsql/backups
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'

    networks:
      - shared-network
  

 

volumes:
  volumes-db:
  files-postgres:
  volumes-backup:
 
networks:
  #hydra-network:
  shared-network:
    external: true

 

