services:
  hydra:
    container_name: dwh-hydra
    image: ghcr.io/hydradatabase/hydra:latest
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hydra123456
      POSTGRES_DB: hydra
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
      - ./files/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    networks:
      - shared-network

networks:
  shared-network:
    external: true
