version: "3"

services:
  cloudbeaver:
    image: dbeaver/cloudbeaver-ee:latest
    container_name: cloudbeaver
    environment:
      - VIRTUAL_HOST= dwh-dbeaver.rihal.dev
      - CLOUDBEAVER_DB_URL=jdbc:postgresql://postgres:5432/cloudbeaver
      - CLOUDBEAVER_DB_USER=cloudbeaver_user
      - CLOUDBEAVER_DB_PASSWORD=cloudbeaver_password
    ports:
      - "8978:8978"  # Expose CloudBeaver web interface on port 8978
    networks:
      - shared-network

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_DB=cloudbeaver
      - POSTGRES_USER=cloudbeaver_user
      - POSTGRES_PASSWORD=cloudbeaver_password
    ports:
      - "5436:5432"  # Expose PostgreSQL on port 5432
    networks:
      - shared-network

networks:
  shared-network:
    external: true
