version: "3"
services:
  cloudbeaver:
    image: dbeaver/cloudbeaver-ee:latest
    container_name: dwh-cloudbeaver
    environment:
      VIRTUAL_HOST: dwh-dbeaver.rihal.dev
      VIRTUAL_PORT: 8978
      CLOUDBEAVER_DB_URL: jdbc:postgresql://postgres:5432/cloudbeaver
      CLOUDBEAVER_DB_USER: cloudbeaver_user
      CLOUDBEAVER_DB_PASSWORD: cloudbeaver_password
    ports:
      - "8978:8978"
    networks:
      - shared-network
      - cloudbeaver-network
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - cloudbeaver_data:/opt/cloudbeaver

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: cloudbeaver
      POSTGRES_USER: cloudbeaver_user
      POSTGRES_PASSWORD: cloudbeaver_password
    ports:
      - "5436:5432"
    networks:
      - cloudbeaver-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "cloudbeaver_user", "-d", "cloudbeaver"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  cloudbeaver_data:
  postgres_data:

networks:
  cloudbeaver-network:
  shared-network:
    external: true
