version: "3"
services:
  cloudbeaver:
    restart: unless-stopped
    hostname: cloudbeaver
    image: $IMAGE_SOURCE/cloudbeaver-ee:${CLOUDBEAVER_VERSION_TAG}
    container_name: dwh-cloudbeaver
    deploy:
      replicas: 1  
    volumes:
      - cloudbeaver:/opt/cloudbeaver/workspace
    environment:
      - VIRTUAL_HOST=dwh-cloudbeaver.rihal.dev
      - CLOUDBEAVER_DB_URL=jdbc:postgresql://postgres:5432/cloudbeaver
      - CLOUDBEAVER_DB_USER=cloudbeaver_user
      - CLOUDBEAVER_DB_PASSWORD=cloudbeaver_password
      - CLOUDBEAVER_DB_SCHEMA=public
      - CLOUDBEAVER_DB_DRIVER=${CLOUDBEAVER_DB_DRIVER}
      - CLOUDBEAVER_DB_URL=${CLOUDBEAVER_DB_URL}
      - CLOUDBEAVER_DB_USER=${CLOUDBEAVER_DB_USER}
      - CLOUDBEAVER_DB_PASSWORD=${CLOUDBEAVER_DB_PASSWORD}
      - CLOUDBEAVER_DB_SCHEMA=${CLOUDBEAVER_DB_SCHEMA}
      - CLOUDBEAVER_QM_DB_DRIVER=${CLOUDBEAVER_QM_DB_DRIVER}
      - CLOUDBEAVER_QM_DB_URL=${CLOUDBEAVER_QM_DB_URL}
      - CLOUDBEAVER_QM_DB_USER=${CLOUDBEAVER_QM_DB_USER}
      - CLOUDBEAVER_QM_DB_PASSWORD=${CLOUDBEAVER_QM_DB_PASSWORD}
      - CLOUDBEAVER_QM_DB_SCHEMA=${CLOUDBEAVER_QM_DB_SCHEMA}
    expose:
      - "8978"  # Expose the CloudBeaver port
    depends_on:
      - postgres
    networks:
      - cloudbeaver-network
      - shared-network

  postgres:
    restart: unless-stopped
    hostname: postgres
    image: dbeaver/cloudbeaver-postgres:16  # Change if using a different image
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist PostgreSQL data
      - ./cloudbeaver-db-init.sql:/docker-entrypoint-initdb.d/cb-init.sql  # Initialize database with SQL file
    environment:
      - POSTGRES_DB=cloudbeaver
      - POSTGRES_USER=cloudbeaver_user
      - POSTGRES_PASSWORD=cloudbeaver_password
    expose:
      - "5432"  # Expose PostgreSQL port
    networks:
      - cloudbeaver-network

volumes:
  cloudbeaver:
  postgres_data:

networks:
  cloudbeaver-network:
  shared-network:
    external: true
