version: "3"

volumes:
  cloudbeaver: {}
  postgres_data: {}
  nginx_ssl_data: {}
  nginx_conf_data: {}

networks:
  cloudbeaver-private-net:
  shared-network:
    external: true

services:
  
  cloudbeaver:
    restart: unless-stopped
    hostname: cloudbeaver
    image: $IMAGE_SOURCE/cloudbeaver-ee:${CLOUDBEAVER_VERSION_TAG}
    deploy:
      replicas: ${REPLICA_COUNT_EE:-1}
    volumes:
      - cloudbeaver:/opt/cloudbeaver/workspace
    environment:
      - VIRTUAL_HOST=dwh-dbeaver.rihal.dev
      - VIRTUAL_PORT=8978
      - CLOUDBEAVER_DB_DRIVER=${CLOUDBEAVER_DB_DRIVER}
      - CLOUDBEAVER_DB_URL=${CLOUDBEAVER_DB_URL}
      - CLOUDBEAVER_DB_USER=${CLOUDBEAVER_DB_USER}
      - CLOUDBEAVER_DB_PASSWORD=${CLOUDBEAVER_DB_PASSWORD}
      - CLOUDBEAVER_DB_SCHEMA=${CLOUDBEAVER_DB_SCHEMA}
      - CLOUDBEAVER_QM_DB_DRIVER=${CLOUDBEAVER_QM_DB_DRIVER}
      - CLOUDBEAVER_QM_DB_URL=${CLOUDBEAVER_QM_DB_URL}
      - CLOUDBEAVER_QM_DB_USER=${CLOUDBEAVER_QM_DB_USER}
      - CLOUDBEAVER_QM_DB_PASSWORD=${CLOUDBEAVER_QM_DB_PASSWORD}
      - CLOUDBEAVER_QM_DB_SCHEMA=${CLOUDBEAVER_QM_DB_SCHEMA}
    #expose:
      #- ${CLOUDBEAVER_SERVICE_PORT:-8978}
    depends_on:
      - postgres
    networks:
      - cloudbeaver-private-net
    

  postgres:
    restart: unless-stopped
    hostname: postgres
    image: ${IMAGE_SOURCE:-dbeaver}/cloudbeaver-postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./cloudbeaver-db-init.sql:/docker-entrypoint-initdb.d/cb-init.sql
    environment:
      - POSTGRES_DB=cloudbeaver
      - POSTGRES_USER=${CLOUDBEAVER_DB_USER}
      - POSTGRES_PASSWORD=${CLOUDBEAVER_DB_PASSWORD}
    ports:
      - 6300:5432
    networks:
      - cloudbeaver-private-net
      


