version: "3.8"
services:  
      

  cloudbeaver:
    restart: always
    #hostname: cloudbeaver
    image: dbeaver/cloudbeaver:latest  # Official free version image
    container_name: dwh-cloudbeaver
    #deploy:
      #replicas: 1
    volumes:
      - cloudbeaver:/opt/cloudbeaver/workspace
    environment:
      - VIRTUAL_HOST=dwh-cloudbeaver.rihal.dev
      - CLOUDBEAVER_DB_URL=${CLOUDBEAVER_DB_URL}
      - CLOUDBEAVER_DB_USER=${CLOUDBEAVER_DB_USER}
      - CLOUDBEAVER_DB_PASSWORD=${CLOUDBEAVER_DB_PASSWORD}
      - CLOUDBEAVER_DB_SCHEMA=${CLOUDBEAVER_DB_SCHEMA}
    expose:
      - "8978"
    ports:
       - '8978:8978'
    depends_on:
      - postgres
    networks:
      - cloudbeaver-network
      - shared-network

  postgres:
    restart: unless-stopped
    hostname: postgres
    image: postgres:13  # Official PostgreSQL image
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./cloudbeaver-db-init.sql:/docker-entrypoint-initdb.d/cb-init.sql
    environment:
      - POSTGRES_DB=cloudbeaver
      - POSTGRES_USER=${CLOUDBEAVER_DB_USER}
      - POSTGRES_PASSWORD=${CLOUDBEAVER_DB_PASSWORD}
    expose:
      - "5432"
    networks:
      - cloudbeaver-network

volumes:
  cloudbeaver:
  postgres_data:
networks:
  default:
    name: ${APP_NETWORK}
    external: true
networks:
  cloudbeaver-network:
  shared-network:
    external: true
