version: "3.8"
services:  
      

  cloudbeaver:
    restart: always
    hostname: cloudbeaver
    image: dbeaver/cloudbeaver:latest  
    container_name: dwh-cloudbeaver
    volumes:
      - cloudbeaver:/opt/cloudbeaver/workspace
    environment:
      - VIRTUAL_HOST=dwh-cloudbeaver.rihal.dev
    expose:
      - "8978"
    ports:
       - '8978:8978'
    depends_on:
      - postgres
    networks:
      - cloudbeaver-network
      - shared-network

  postgres:
    restart: always
    hostname: postgres
    image: postgres:13  
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./cloudbeaver-db-init.sql:/docker-entrypoint-initdb.d/cb-init.sql
    environment:
      - POSTGRES_DB=cloudbeaver
      - POSTGRES_USER=${CLOUDBEAVER_DB_USER}
      - POSTGRES_PASSWORD=${CLOUDBEAVER_DB_PASSWORD}
    expose:
      - "5432"
    networks:
      - cloudbeaver-network

volumes:
  cloudbeaver:
  postgres_data:

networks:
  cloudbeaver-network:
  shared-network:
    external: true
