version: "3"
services:
  cloudbeaver:
    restart: unless-stopped
    hostname: cloudbeaver
    image: dbeaver/cloudbeaver:latest  # Free version of CloudBeaver
    container_name: dwh-cloudbeaver
    deploy:
      replicas: 1  
    volumes:
      - cloudbeaver:/opt/cloudbeaver/workspace  # Persist CloudBeaver workspace data
    environment:
      - VIRTUAL_HOST=dwh-cloudbeaver.rihal.dev
      - CLOUDBEAVER_DB_URL=jdbc:postgresql://postgres:5432/cloudbeaver
      - CLOUDBEAVER_DB_USER=cloudbeaver_user
      - CLOUDBEAVER_DB_PASSWORD=cloudbeaver_password
      - CLOUDBEAVER_DB_SCHEMA=public  # You can specify the schema if needed
    expose:
      - "8978"  # Expose the CloudBeaver web interface on port 8978
    depends_on:
      - postgres
    networks:
      - cloudbeaver-network
      - shared-network

  postgres:
    restart: unless-stopped
    hostname: postgres
    image: dbeaver/cloudbeaver-postgres:16  # Use the cloudbeaver-postgres image
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist PostgreSQL data
      - ./cloudbeaver-db-init.sql:/docker-entrypoint-initdb.d/cb-init.sql  # Initialize database with SQL file
    environment:
      - POSTGRES_DB=cloudbeaver
      - POSTGRES_USER=cloudbeaver_user
      - POSTGRES_PASSWORD=cloudbeaver_password
    expose:
      - "5432"  # Expose PostgreSQL port
    networks:
      - cloudbeaver-network

volumes:
  cloudbeaver:
  postgres_data:

networks:
  cloudbeaver-network:
  shared-network:
    external: true
