version: "3.8"
services:
  db:
    image: postgres
    container_name: dwh-postgres-db
    restart: always
    ports:
      - "5438:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    networks:
      - pgadmin-network
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      VIRTUAL_HOST: dwh-pgadmin.rihal.dev
      VIRTUAL_PORT: 8888
      PGADMIN_DEFAULT_EMAIL: nalmawali97@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - pgadmin-network
      - shared-network
    

volumes:
  local_pgdata:
  pgadmin-data:


networks:
  pgadmin-network:
  shared-network:
    external: true
