version: '3.8'
#https://medium.com/towards-data-engineering/running-a-postgresql-and-pgadmin4-instance-using-docker-compose-c6dd6e6e03bb
#https://github.com/matschik/docker-compose-postgres-pgadmin/tree/main
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    networks:
      - pgadmin-network
    ports:
      - "5437:5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      VIRTUAL_HOST: dwh-pgadmin.rihal.dev
      VIRTUAL_PORT: 5050
      PGADMIN_DEFAULT_EMAIL: nalmawali97@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    networks:
      - pgadmin-network
      - shared-network
      
    ports:
      - "5050:80"

volumes:
  postgres-data:

networks:
  pgadmin-network:
  shared-network:
    external: true
