# Use a Python base image
FROM python:3.9-slim

# Set environment variables
ENV DBT_PROFILES_DIR=/app/dbt

# Set working directory
WORKDIR /app/dbt

# Copy project files
COPY ./dbt/ /app/dbt

# Install dbt and dbt-clickhouse adapter
RUN pip install --no-cache-dir dbt-core dbt-clickhouse

# Default command
CMD ["bash", "-c", "dbt deps && dbt seed && dbt run && dbt test"]
