name: ${DEPLOYMENT_NAME}
services:
  db:
    image: pgduckdb/pgduckdb:16-main
    container_name: ${DEPLOYMENT_NAME}-db
    ports:
       - 5444:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: duckdb
    volumes:
      - config:/etc/postgresql
      - data:/var/lib/postgresql/data
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    restart: always
 
volumes:
  data:
  config:
 
networks:
  default:
    name: shared-network
    external: true