version: "3.8"
#https://github.com/compose-spec/compose-spec/blob/master/spec.md#using-extensions-as-fragments
x-logging:
  &default-logging
  options:
    max-size: "100m"
    max-file: "5"
  driver: json-file
name: ${DEPLOYMENT_NAME}
services:
  # Initialization service
  airbyte-init:
    image: airbyte/init:${VERSION}
    logging: *default-logging
    container_name: ${DEPLOYMENT_NAME}-airbyte-init
    command: /bin/sh -c "./scripts/create_mount_directories.sh /local_parent ${HACK_LOCAL_ROOT_PARENT} ${LOCAL_ROOT}"
    environment:
      - LOCAL_ROOT=${LOCAL_ROOT}
      - HACK_LOCAL_ROOT_PARENT=${HACK_LOCAL_ROOT_PARENT}
    volumes:
      - ${HACK_LOCAL_ROOT_PARENT}:/local_parent

  # Bootloader service
  airbyte-bootloader:
    image: airbyte/bootloader:${VERSION}
    logging: *default-logging
    container_name: ${DEPLOYMENT_NAME}-airbyte-bootloader
    environment:
      - AIRBYTE_VERSION=${VERSION}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_URL=jdbc:postgresql://${DEPLOYMENT_NAME}-airbyte-db:5432/airbyte
      - DATABASE_USER=${DATABASE_USER}
      - LOG_LEVEL=${LOG_LEVEL}
    depends_on:
      airbyte-init:
        condition: service_completed_successfully
    networks:
      - airbyte-network

  # PostgreSQL Database service
  airbyte-db:
    image: airbyte/db:${VERSION}
    logging: *default-logging
    container_name: ${DEPLOYMENT_NAME}-airbyte-db
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
    volumes:
      - airbyte-db:/var/lib/postgresql/data
    networks:
      - airbyte-network

  # Worker service
  airbyte-worker:
    image: airbyte/worker:${VERSION}
    logging: *default-logging
    container_name: ${DEPLOYMENT_NAME}-airbyte-worker
    restart: unless-stopped
    environment:
      - AIRBYTE_VERSION=${VERSION}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_URL=jdbc:postgresql://${DEPLOYMENT_NAME}-airbyte-db:5432/airbyte
      - DATABASE_USER=${DATABASE_USER}
      - TEMPORAL_HOST=${DEPLOYMENT_NAME}-airbyte-temporal:7233
    volumes:
      - airbyte-workspace:${WORKSPACE_ROOT}
    depends_on:
      airbyte-bootloader:
        condition: service_completed_successfully
    networks:
      - airbyte-network

  # Server service
  server:
    image: airbyte/server:${VERSION}
    logging: *default-logging
    container_name: ${DEPLOYMENT_NAME}-airbyte-server
    restart: unless-stopped
    environment:
      - AIRBYTE_VERSION=${VERSION}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_URL=jdbc:postgresql://${DEPLOYMENT_NAME}-airbyte-db:5432/airbyte
      - DATABASE_USER=${DATABASE_USER}
      - TEMPORAL_HOST=${DEPLOYMENT_NAME}-airbyte-temporal:7233
      - VIRTUAL_HOST=${DEPLOYMENT_NAME}-airbyte-server.rihal.dev
      - VIRTUAL_PORT=8001
    volumes:
      - airbyte-workspace:${WORKSPACE_ROOT}
      - airbyte-data:${CONFIG_ROOT}
    depends_on:
      airbyte-bootloader:
        condition: service_completed_successfully
    networks:
      - airbyte-network
      - shared-network

  # WebApp service
  webapp:
    image: airbyte/webapp:${VERSION}
    logging: *default-logging
    container_name: ${DEPLOYMENT_NAME}-airbyte-webapp
    restart: unless-stopped
    ports:
      - 8000:80
    environment:
      - VIRTUAL_HOST=${DEPLOYMENT_NAME}-airbyte-webapp.rihal.dev
      - VIRTUAL_PORT=80
      - AIRBYTE_VERSION=${VERSION}
    depends_on:
      airbyte-bootloader:
        condition: service_completed_successfully
    networks:
      - airbyte-network
      - shared-network

  # Temporal service
  airbyte-temporal:
    image: airbyte/temporal:${VERSION}
    logging: *default-logging
    container_name: ${DEPLOYMENT_NAME}-airbyte-temporal
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PWD=${DATABASE_PASSWORD}
    volumes:
      - dynamicconfig:/etc/temporal/config/dynamicconfig
    networks:
      - airbyte-network

  # Cron service
  airbyte-cron:
    image: airbyte/cron:${VERSION}
    logging: *default-logging
    container_name: ${DEPLOYMENT_NAME}-airbyte-cron
    restart: unless-stopped
    environment:
      - AIRBYTE_VERSION=${VERSION}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_URL=jdbc:postgresql://${DEPLOYMENT_NAME}-airbyte-db:5432/airbyte
      - DATABASE_USER=${DATABASE_USER}
    volumes:
      - airbyte-workspace:${WORKSPACE_ROOT}
    depends_on:
      airbyte-bootloader:
        condition: service_completed_successfully
    networks:
      - airbyte-network

volumes:
  dynamicconfig:
  airbyte-workspace:
    name: ${WORKSPACE_DOCKER_MOUNT}
  airbyte-data:
    name: ${DATA_DOCKER_MOUNT}
  airbyte-db:
    name: ${DB_DOCKER_MOUNT}

networks:
  airbyte-network:
  shared-network:
    external: true
